# Generated by Django 5.2.3 on 2025-06-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='entered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
