name: rocket-assess
services:
- name: backend
  source_dir: /backend
  github:
    repo: Robbie-Cutty/RocketAssess
    branch: main
  run_command: gunicorn --worker-tmp-dir /dev/shm core.wsgi
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: SECRET_KEY
    scope: RUN_TIME
    type: SECRET
  - key: DEBUG
    scope: RUN_TIME
    value: "False"
  - key: DB_NAME
    scope: RUN_TIME
    value: "${db.DATABASE}"
  - key: DB_USER
    scope: RUN_TIME
    value: "${db.USERNAME}"
  - key: DB_PASSWORD
    scope: RUN_TIME
    value: "${db.PASSWORD}"
  - key: DB_HOST
    scope: RUN_TIME
    value: "${db.HOSTNAME}"
  - key: DB_PORT
    scope: RUN_TIME
    value: "${db.PORT}"
  - key: CORS_ALLOWED_ORIGINS
    scope: RUN_TIME
    value: "https://rocket-assess-frontend.ondigitalocean.app"
  http_port: 8000

- name: frontend
  source_dir: /frontend
  github:
    repo: Robbie-Cutty/RocketAssess
    branch: main
  build_command: npm install && npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs

databases:
- name: db
  engine: PG
  version: "15"
  production: false
  cluster_name: rocket-assess-db 